### ISSUE TITLE
Vectype Fps

### ISSUE THREAD

**Issue by ansariyusuf** [hcji/PyFingerprint#10]
FileNotFoundError: [Errno 2] No such file or directory: 'PyFingerprint/Mol2vec/model_300dim.pkl'

I have checked that the pkl file is available at the correct location. I have also tried hardcoding the path in the Mol2Vec.py. Kindly help!

Yusuf

**Comment by hcji** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'PyFingerprint/Mol2vec/model_300dim.pkl'
> 
> I have checked that the pkl file is available at the correct location. I have also tried hardcoding the path in the Mol2Vec.py. Kindly help!
> 
> Yusuf

Has been fixed. Can you uninstall the old version and reinstall for testing?
