### ISSUE TITLE
canonical or isomeric SMILES sequence for fingerprint calculation

### ISSUE THREAD

**Issue by kuandannyan** [hcji/PyFingerprint#11]
Dear authors (@samgoldman97  @hcji )

Thank you for the great work. 

I was reading through the example for fingerprint generation. Is the SMILES sequence used for input supposed to be canonical or isomeric SMILES sequence?

Thank you in advance.

Best Regards

Kuan

**Comment by samgoldman97** [comment]
Hi Kuan, 
I've only written a few modifications to @hcji's original work to get access to additional fingerprints of interest. I would suggest isomeric smiles if you care about the chirality of your input molecules, though I am unsure which fingerprints consider chiral features. It would be best to search for the original fingerprint descriptions directly.

Sam

**Comment by kuandannyan** [comment]
Dear Sam,

Thank you for the info. I would guess so as isomeric SMILES is more commonly used. But it won’t make huge difference for the fingerprint generation as long as I keep the input SMILES type the same I guess.

Again. Thank you for the follow up.

Best Regards

Kuan Yan
