### ISSUE TITLE
KlekotaRothFingerprinter missing

### ISSUE THREAD

**Issue by jvansan** [hcji/PyFingerprint#5]
I would like to use your library to calculate Klekota-Roth and other CDK Fingerprints but I am experiencing an error.

```
/usr/local/anaconda3/envs/atlas/lib/python3.7/site-packages/PyFingerprint/CDK_Fingerprint.py in cdk_fingerprint(smi, fp_type, size, depth, output)
     46                             , "hybridization":cdk.fingerprint.HybridizationFingerprinter(size, depth)
     47                             , "lingo":cdk.fingerprint.LingoFingerprinter(depth)
---> 48                             , "klekota-roth":cdk.fingerprint.KlekotaRothFingerprinter()
     49                             , "shortestpath":cdk.fingerprint.ShortestPathFingerprinter(size)
     50                             , "signature": cdk.fingerprint.SignatureFingerprinter(depth)

AttributeError: Java package 'org.openscience.cdk.fingerprint' has no attribute 'KlekotaRothFingerprinter'
```

It seems that for some reason the KlekotaRothFingerprinter is not available from the CDK jar. I dug into this a little further and tried to use the latest CDK 2.3 release instead using jpype directly, and experienced the same issue. The source code for CDK still includes the KlekotaRothFingerPrinter, so I don't know why it would be unavailable from the jar. Have you experienced any similar issues?

**Tech Specs:**
Macbook Pro (macOS 10.15.7)
Python 3.7.8 (Anaconda)
Java Version 8 Update 261

**Comment by jvansan** [comment]
Just to expand a little more, I tried to run the same method from a very simple Java app:

```
package org.jvansan.cdk.explorer;

import org.openscience.cdk.smiles.SmilesParser;
import org.openscience.cdk.DefaultChemObjectBuilder;
import org.openscience.cdk.exception.CDKException;
import org.openscience.cdk.exception.InvalidSmilesException;
import org.openscience.cdk.interfaces.IAtomContainer;
import org.openscience.cdk.fingerprint.IBitFingerprint;
import org.openscience.cdk.fingerprint.KlekotaRothFingerprinter;


public class App 
{
    public static void main( String[] args ) throws CDKException
    {
    	IAtomContainer mol = null;
    	String smi = "c1ccccc1";
    	SmilesParser sp  = new SmilesParser(DefaultChemObjectBuilder.getInstance());
    	KlekotaRothFingerprinter krfp = new KlekotaRothFingerprinter();
    	try {
			mol = sp.parseSmiles(smi);
			System.out.println( "Benzene has " + mol.getAtomCount() + " atoms." );
			IBitFingerprint fp = krfp.getBitFingerprint(mol);

			System.out.println( fp.size() );

		} catch (InvalidSmilesException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
}

```

And had no problems...

**Comment by hcji** [comment]
> Just to expand a little more, I tried to run the same method from a very simple Java app:
> 
> ```
> package org.jvansan.cdk.explorer;
> 
> import org.openscience.cdk.smiles.SmilesParser;
> import org.openscience.cdk.DefaultChemObjectBuilder;
> import org.openscience.cdk.exception.CDKException;
> import org.openscience.cdk.exception.InvalidSmilesException;
> import org.openscience.cdk.interfaces.IAtomContainer;
> import org.openscience.cdk.fingerprint.IBitFingerprint;
> import org.openscience.cdk.fingerprint.KlekotaRothFingerprinter;
> 
> 
> public class App 
> {
>     public static void main( String[] args ) throws CDKException
>     {
>     	IAtomContainer mol = null;
>     	String smi = "c1ccccc1";
>     	SmilesParser sp  = new SmilesParser(DefaultChemObjectBuilder.getInstance());
>     	KlekotaRothFingerprinter krfp = new KlekotaRothFingerprinter();
>     	try {
> 			mol = sp.parseSmiles(smi);
> 			System.out.println( "Benzene has " + mol.getAtomCount() + " atoms." );
> 			IBitFingerprint fp = krfp.getBitFingerprint(mol);
> 
> 			System.out.println( fp.size() );
> 
> 		} catch (InvalidSmilesException e) {
> 			// TODO Auto-generated catch block
> 			e.printStackTrace();
> 		}
>     }
> }
> ```
> 
> And had no problems...

I update to Java JDK 11, and JPype1 to version 1.2.1. It can work properly now.
