### ISSUE TITLE
java.lang.NullPointerException: java.lang.NullPointerException: atom has unset atom type

### ISSUE THREAD

**Issue by naeemmrz** [hcji/PyFingerprint#9]
Hello,

I'm receiving this error in one of the CDKtype fingerprints calculations, the log shows the error to occur in the line 
---> 75     fp_obj = fingerprinter.getBitFingerprint(mol)
I couldn't figure out how to print the smiles after each calculation from smlist so I can't say if it's a smiles issue or something else. All smiles were preprocessed by RDKit and those that failed this step were removed, any idea what might be going on or how I could diagnose it? The code is the exact copy of the get_fingerpints() that's provided in the README file.

**Comment by hcji** [comment]
I will update for automatically detect and ignore the unsuccessful SMILES as soon as possible, but for now you can use loop to handle your SMILES one by one with `get_fingerprint` function

**Comment by recursingfeynman** [comment]
Hi! I have same issue. Did you find a solution? 

> Hello,
> 
> I'm receiving this error in one of the CDKtype fingerprints calculations, the log shows the error to occur in the line ---> 75 fp_obj = fingerprinter.getBitFingerprint(mol) I couldn't figure out how to print the smiles after each calculation from smlist so I can't say if it's a smiles issue or something else. All smiles were preprocessed by RDKit and those that failed this step were removed, any idea what might be going on or how I could diagnose it? The code is the exact copy of the get_fingerpints() that's provided in the README file.
